apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-claim-lh
spec:
  storageClassName: longhorn
  accessModes:
#    - ReadWriteOnce
    - ReadWriteMany
  resources:
    requests:
      storage: 50Mi