apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: demovolpvlh
spec:
  serviceName: demovolpvlh
  selector:
    matchLabels:
      app: demovolpvlh
  replicas: 1
  template:
    metadata:
      labels:
        app: demovolpvlh
    spec:
      containers:
        - name: demovolpvlh
          image: alpine
          command: ["tail","-f","/dev/null"]
          volumeMounts:
          - name: data
            mountPath: /data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: example-claim-lh